### ISSUE TITLE
should show up in navigation panel

### ISSUE THREAD

**Issue by grafst** [awcodes/filament-versions#11]
widget works great, but i don't see anything in navigation panel...
am I doing something wrong?
<img width="1074" alt="2023-03-23_20-55-14" src="https://user-images.githubusercontent.com/8471055/227336807-cf1f24ce-e635-4fae-b8f8-a573a0c3bba1.png">

**Comment by awcodes** [comment]
Is there really nothing there or is it just in the wrong text color?

**Comment by awcodes** [comment]
I've just tagged a 1.1.0 release, see if that works for you, but I can't replicate this issue in the Filament Demo.

**Comment by grafst** [comment]
<img width="1280" alt="2023-06-14_20-30-43" src="https://github.com/awcodes/filament-versions/assets/8471055/754f8bb5-26da-4c57-8aaf-cccccd5355b3">
in a new project it's working now. don't know what went wrong there previously.
small nitpick: would be cool if it was 1 line...

**Comment by awcodes** [comment]
There's no way to make it fit on one line. :) Especially if you add more items to it.

**Comment by grafst** [comment]
allright then :)
