### ISSUE TITLE
sidebar.end display versions by config

### ISSUE THREAD

**Issue by invaders-xx** [awcodes/filament-versions#4]
Hi,

That would be great if we could display the versions in the sidebar based on a config parameter. Not very tricky, if you accept, I can PR ?

**Comment by awcodes** [comment]
Are you wanting to hide them in the side bar? because that's kinda the point of the plugin.

**Comment by invaders-xx** [comment]
The thing is I have multiple context and I would like to only display the versions using the widget, because I don't want any user to see the versions. The best behaviour for me would probably be to display versions based on user profile. I don't know if I make myself clear. But anyway, I understand if you don't want to implement that.

**Comment by invaders-xx** [comment]
You'e right, I will make my own widget. never mind. And I would like to thank you for all the great and useful plugins you made. Great Job!
