### ISSUE TITLE
Add $columnSpan to the widget

### ISSUE THREAD

**Issue by MarJose123** [awcodes/filament-versions#8]
Can we add a support to customize widget width?

```
protected int | string | array $columnSpan = 'full';
```

**Comment by awcodes** [comment]
The widget extends Filament's widget class so this is already in place.

**Comment by MarJose123** [comment]
> The widget extends Filament's widget class so this is already in place.

I extended the class that you have, it duplicate the widget.

**Comment by awcodes** [comment]
Sorry, i'm not sure what you're asking here.
