### ISSUE TITLE
Option - Hide in left menu

### ISSUE THREAD

**Issue by hejcmichal** [awcodes/filament-versions#9]
Create callable method to disible showing in left menu via boot method. Sometimes all you need is widget.

**Comment by awcodes** [comment]
Should be good to go now. Make sure to do this in the `register` method. `boot` is too late in the lifecycle.

```php
use FilamentVersions\Facades\FilamentVersions;

public function register()
{
    FilamentVersions::registerNavigationView(false);
}
```
